spring:
  main:
    banner-mode: off
  sql:
    init:
      mode: embedded
  jpa:
    show-sql: false
  # Set template for datasource. Values to be provided by environment properties
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD} #Change value if the password is different
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 60000
      maximum-pool-size: 90


access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH:#{'access_token_keys/private_key.key'}}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH:#{'access_token_keys/public_key.key'}}

# Default cors config
web:
  cors:
    allowed-origins:
      - "*" # allow all origins
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "*"

