spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  sql:
    init:
      mode: embedded
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#    database: default
#    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 60000
      maximum-pool-size: 90

#logging:
#  pattern:
#    console: %d{MM-dd HH:mm:ss} - %logger{36} - %msg%n