# This profile is only used for docker postgresql db during ci procedure
# Do not use for local environment
spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true


ACCESS_TOKEN_PRIVATE_KEY_PATH: "access_token_keys/private_key.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access_token_keys/public_key.key"
DB_HOST: "localhost"
DB_USERNAME: "postgres"
DB_PASSWORD: "password"
DB_NAME: "test_db"
DB_PORT: 7100